import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Providers } from "./providers";
import NavBar from '@/components/chakraUI/navbar';
import { ReduxProvider } from '@/redux/provider/ReduxProvider';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Gerenciador Zazuu',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <Providers>
            <NavBar />
            {children}
          </Providers>
        </ReduxProvider>
      </body>
    </html>
  );
}
